//! Build-time sizing: read `sizing.toml`, validate invariants, and emit typed
//! constants into `OUT_DIR/sizing_consts.rs`. These are the compile-time
//! defaults; the runtime override surface lives in `main.rs` via conflaguration.
//!
//! Per-key build override: `SIZING_<SECTION>_<KEY>`
//! (e.g. `SIZING_RING_CAPACITY=2048 cargo build`).

use std::env;
use std::fs;
use std::path::Path;
use std::path::PathBuf;

use toml::Value;

fn get_int(table: &Value, section: &str, key: &str) -> u64 {
    let raw = table
        .get(section)
        .and_then(|sec| sec.get(key))
        .and_then(Value::as_integer)
        .unwrap_or_else(|| panic!("sizing.toml: missing or non-integer [{section}].{key}"));
    u64::try_from(raw).unwrap_or_else(|_| panic!("[{section}].{key} = {raw} must be non-negative"))
}

// read the toml value, then let an optional SIZING_<SECTION>_<KEY> env var win.
fn resolve(table: &Value, section: &str, key: &str) -> u64 {
    let env_name = format!("SIZING_{}_{}", section.to_ascii_uppercase(), key.to_ascii_uppercase());
    println!("cargo:rerun-if-env-changed={env_name}");
    if let Ok(raw) = env::var(&env_name) {
        return raw.parse().unwrap_or_else(|err| panic!("{env_name} = {raw}: {err}"));
    }
    get_int(table, section, key)
}

fn require_pow2(name: &str, value: u64) -> u64 {
    assert!(value.is_power_of_two(), "{name} must be a power of two; got {value}");
    value
}

fn require_nonzero(name: &str, value: u64) -> u64 {
    assert!(value > 0, "{name} must be non-zero; got {value}");
    value
}

fn emit_sizing_consts(out_dir: &Path) {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR set by cargo");
    let toml_path = PathBuf::from(&manifest_dir).join("sizing.toml");
    println!("cargo:rerun-if-changed=sizing.toml");

    let text = fs::read_to_string(&toml_path).unwrap_or_else(|err| panic!("read {}: {err}", toml_path.display()));
    let root: Value = text.parse().unwrap_or_else(|err| panic!("parse {}: {err}", toml_path.display()));

    let ring_capacity = require_pow2("ring.capacity", resolve(&root, "ring", "capacity"));
    let flush_interval_micros = require_nonzero("pump.flush_interval_micros", resolve(&root, "pump", "flush_interval_micros"));

    let generated = format!(
        "// AUTO-GENERATED by build.rs from sizing.toml. DO NOT EDIT.\n\
         /// Ring buffer length, validated as a power of two at build time.\n\
         pub const RING_CAPACITY: usize = {ring_capacity};\n\
         /// Default pump flush interval in microseconds.\n\
         pub const FLUSH_INTERVAL_MICROS: u64 = {flush_interval_micros};\n",
    );

    let out_path = out_dir.join("sizing_consts.rs");
    fs::write(&out_path, generated).unwrap_or_else(|err| panic!("write {}: {err}", out_path.display()));
}

fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR set by cargo"));
    emit_sizing_consts(&out_dir);
}
